    # Utiliza uma imagem leve do Nginx para servir os ficheiros estáticos
    FROM nginx:alpine
    # Copia o ficheiro da interface para a pasta pública do Nginx
    COPY ./index.html /usr/share/nginx/html/index.html
    # Expõe a porta 80 (padrão do Nginx)
    EXPOSE 80
    

